const itemDatabase = [
    //Desserts
    {id:"apple_pie",
    name: "Apple Pie",
    price: 7.99,
    description: "Treat yourself with a large slice of our homemade, crispy apple pie, made fresh from the oven, with a buttery crust, and a sweet apple filling. Lightly dusted with powered sugar.",
    imgPath: "images/ApplePie.png"},
    {id:"brownie",
    name: "Brownie",
    price: 6.99,
    description: "Rich, moist chocolate brownies to die for, with a fudgy texture. Served with a generous drizzle of high quality chocolate syrup.",
    imgPath: "images/Brownies.png"},
    {id:"lava_cake",
    name: "Lava Cake",
    price: 8.99,
    description: "Fresh, heavenly chocolate cake with a rich, liquid berry center. Served with a fresh cut strawberry and lightly sprinkled with powdered sugar.",
    imgPath: "images/LavaCake.png"},

    
    //Burgers
    {id:"gd_burger",
    name: "Game Day Burger",
    price: 10.99,
    description: "A juicy, 1/4 pound burger with a thick patty, cheese, our signature sauce, bacon, onion rings, fresh onions, lettuce, pickles, and tomatoes. Topped with a sesame seed bun.",
    imgPath: "images/HouseSpecialBurger.png"},
    {id:"bacon_burger",
    name: "Bacon Burger",
    price: 10.99,
    description: "Savor the sizzle of bacon atop our classic burger—a perfect harmony of juicy beef, melted cheese, and crispy, smoky bacon on a toasted bun.",
    imgPath: "images/BaconBurger.png"},
    {id: "bbq_burger",
    name: "BBQ Burger",
    price: 9.99,
    description: "A 1/4 pound burger with a thick patty, cheddar cheese, bbq sauce, and fresh lettuce and tomatoes, all topped with a toasted sesame seed bun.",
    imgPath: "images/bbqBurger.png"},
    {id: "ms_burger",
    name: "Mushroom Swiss Burger",
    price: 9.99,
    description: "A 1/4 pound burger filled with thick-cut bacon, sautéd mushrooms, a juicy patty, swiss cheese, and fresh lettuce, tomatos, and pickles. Served with our signature sauce.",
    imgPath: "images/MushroomSwissBurger.png"},


    //Combos
    {id:"db_combo",
    name: "Double Burger Combo",
    price: 12.99,
    description: "This amazing combo comes with our tantalizing double decker burger and a side of our mouth watering fries and a softdrink. This combo can have any of our sides switched out with the fries to make the combo more worthwile for you.",
    imgPath: "images/DoubleBurgerCombo.png"},
    {id:"pork_combo",
    name: "Porkchop Combo",
    price: 11.99,
    description: "This combo comes with our slow-cooked, juicy porkchop topped with our flavorful seasoning, and our fantastic fries.",
    imgPath: "images/PorkCombo.png"},
    {id:"tw_combo",
    name: "Tradional Wing Combo",
    price: 11.99,
    description: "Juicy chicken wings deep fried and lightly seasoned with garlic, salt, and pepper and drizzled in our traditional sauce, comes with a side of our mouth watering fries and a softdrink.",
    imgPath: "images/TradionalWingCombo.png"},
    {id:"cs_combo",
    name: "Chicken Strips Combo",
    price: 11.99,
    description: "A platter of perfectly juicy chicken tenders, deep fried to perfect crispiness, and lightly seasoned with salt, garlic, and pepper. Comes with fries and coleslaw.",
    imgPath: "images/ChickenStripsCombo.png"},


    //Wings
    {id:"gourmet_wings",
    name: "Gourmet Wings",
    price: 13.99,
    description: "Tender chicken wings tossed in our spicy, tangy buffalo sauce. Great if you like a strong kick of flavor. Pair it with one of our sides for an unmatched experiance.",
    imgPath:"images/GourmetWings.png"},
    {id:"bbq_wings",
    name:"BBQ Wings",
    price: 10.99,
    description: "Tender chicken wings tossed in our housemade bbq sauce. Great if you like a strong kick of smokey bbq flavor.",
    imgPath: "images/bbqWings.png"},
    {id:"plain_wings",
    name:"Plain Wings",
    price: 9.99,
    description: "Plain, juicy chicken wings deep fried and lightly seasoned with garlic, salt, and pepper, but no sauce. Cooked to a level of crispiness perfection. Comes with your choice of dipping sauce.",
    imgPath: "images/PlainWings.png"},
    {id:"sample_wings",
    name:"Sample Wings Platter",
    price: 12.99,
    description: "All of our incredible wings in one place! Comes with all housemade sauces for a true flavorfull experince.",
    imgPath: "images/VarietyWings.png"},


    //Meats
    {id:"steak",
    name:"Steak",
    price: 12.99,
    description: "Fire seared grilled grass fead ribye based in garlic and rosemerry.",
    imgPath: "images/Steak.png"},
    {id:"chicken",
    name:"Grilled Chicken",
    price: 8.99,
    description: "Freshly grilled chicken, grilled with rosemerry and lemon.",
    imgPath: "images/Chicken.png"},
    {id:"salmon",
    name:"Salmon",
    price: 13.99,
    description: "Perfectly grilled fresh lake caught salmon, seasoned with parsly and lemon.",
    imgPath: "images/Salmon.png"},


    //Sides and Appetizers
    {id:"onion_rings",
    name: "Onion Rings",
    price: 5.99,
    description: "Our mouth-watering onion rings batttered in a precicley seasoned breadcrumb batter. These delicious onion rings come with your choice of dipping sauce for a true flavor sensation.",
    imgPath: "images/OnionRings.png"},
    {id:"fries",
    name: "Fries",
    price: 4.99,
    description: "Thinly sliced potatoes, deep-fried until golden-brown, and delicately dusted with sea salt. Crispy, fluffy perfection in every bite. These fries come with your choice of dipping sauce on the side.",
    imgPath: "images/Fries.png"},
    {id:"chille_fries",
    name: "Chille Fries",
    price: 4.99,
    description: "Our chillie fries are almost a meal! Enjoy a large bowl of our signature fries deepfried to perfection and topped with our spicey ground beef and melted cheese.",
    imgPath: "images/ChilleFries.png"},
    {id:"mozzarella_sticks",
    name:"Mozzarella Sticks",
    price: 5.99,
    description: "Creamy mozzarella coated in a crisp batter and deep-fried to perfection. These Cheesesticks are paired with our mouth-watering red sauce.",
    imgPath: "images/MozzarellaSticks.png"},


    //Kids
    {id:"sliders",
    name:"Sliders",
    price: 6.99,
    description: "Our mini burger sliders come jam-packed with all of the flavors our GameDay burger is known for, but now kid sized!",
    imgPath: "images/Sliders.png"},
    {id:"chicken_nuggets",
    name:"Chicken Nuggets Combo Platter",
    price: 9.99,
    description: "Chicken nuggets, deep fried to perfect crispiness, and lightly seasoned with salt. Comes as a platter to share, and fries with your choice of dipping sauce.",
    imgPath: "images/ChickenNuggetsKids.png"},
    {id:"mac_cheese",
    name:"Mac & Cheese",
    price: 6.99,
    description: "A bowl of cheesy, creamy housemade mac and cheese, topped with a sprinkle of grated parmesian cheese. Perfect for cheese lovers!",
    imgPath: "images/MachCheese.png"},


    //Salads
    {id:"caesar_salad",
    name:"Caesar Salad",
    price: 6.99,
    description: "Our Ceasar Salad comes with croutons, shedded parmesan, romaine lettuce, and our unforgettable ceasar dressing.",
    imgPath: "images/CaesarSalad.png"},
    {id:"chicken_salad",
    name:"Chicken Salad",
    price: 7.99,
    description: "This salad is very similar to our Ceasar Salad. It comes with shedded parmesan, romaine lettuce, flavorfull tomatoes, our unforgettable ranch dressing and of course our mouth-watering chicken to top it all off.",
    imgPath: "images/ChickenSalad.png"},
    {id:"balsamic_salad",
    name:"Balsamic Salad",
    price: 6.99,
    description: "This salad comes with tomatoes, cucumbers, red bell pepper, red onion, feta cheese and out amazing homeade balsamic dressing.",
    imgPath: "images/BalsamicSalad.png"},


    //Sandwiches
    {id:"club_sandwich",
    name:"Club Sandwich",
    price: 7.99,
    description: "A ham, turkey, and bacon sandwich, with mouth watering tomatoes, crunchy lettuce and cheddar cheese",
    imgPath: "images/ClubSandwich.png"},
    {id:"ruben_sandwich",
    name:"Ruben Sandwich",
    price: 8.99,
    description: "Our award winning ruben consists of corned beef, Swiss cheese, sauerkraut, and Russian dressing grilled between slices of pumpernickel rye bread.",
    imgPath: "images/RubenSandwich.png"},
    {id:"pp_sandwich",
    name:"Pulled Pork Sandwich",
    price: 7.99,
    description: "Our signature pulled pork sandwiched between two thick fluffy sesame buns and drissled in our homemade bbq sauce.",
    imgPath: "images/PulledPorkSandwich.png"},
    {id:"cuban_sandwich",
    name:"Cuban Sandwich",
    price: 8.99,
    description: "A satisfying grilled sandwich, our cuban sandwich features layers of sliced ham, roasted pork, Swiss cheese, pickles, and mustard on our crusty Cuban bread.",
    imgPath: "images/CubanSandwich.png"},
    {id:"blt",
    name:"BLT",
    price: 7.99,
    description: "Our thick casian bacon is grilled to perfecton and combined with juciy tomato and fluffy letuce to give you an unmatched flavor sensation.",
    imgPath: "images/BLT.png"},


    //Drinks
    {id:"root_beer",
    name:"Root Beer",
    price: 1.99,
    description: "Our housemade root beer is the perfect drink to wash down your flavorful meal.",
    imgPath: "images/RootBeer.png"},
    {id:"strawberry_lemonade",
    name:"Strawberry Lemonade",
    price: 1.99,
    description: "Our fresh, ice cold strawberry lemonade is just the thing you need to refresh yourself and to cool down on a hot summer day.",
    imgPath: "images/StrawberryLemonade.png"},
];
