const itemDatabase = [
    //Desserts
    {id:"apple_pie",
    name: "Apple Pie",
    price: 6.99,
    description: "A slice of pie with a buttery crust and a sweet apple filling.",
    imgPath: "images/ApplePie.png"},
    {id:"brownie",
    name: "Brownie",
    price: 6.99,
    description: "Chocolate brownies with a fudge-like texture and a drizzle of chocolate syrup.",
    imgPath: "images/Brownies.png"},
    {id:"lava_cake",
    name: "Lava Cake",
    price: 6.99,
    description: "Cake with a liquid chocolate center. Served with a strawberry and sprinkled with powdered sugar.",
    imgPath: "images/LavaCake.png"},

    
    //Burgers
    {id:"gd_burger",
    name: "Game Day Burger",
    price: 10.99,
    description: "A thick burger with our signature sauce, cheese, and fresh tomatoes, lettuce, onions, and pickles",
    imgPath: "images/HouseSpecialBurger.png"},
    {id:"bacon_burger",
    name: "Bacon Burger",
    price: 10.99,
    description: "Savor the sizzle of bacon atop our classic burger—a perfect harmony of juicy beef, melted cheese, and crispy, smoky bacon on a toasted bun.",
    imgPath: "images/BaconBurger.png"},
    {id: "bbq_burger",
    name: "BBQ Burger",
    price: 9.99,
    description: "Experience the tanginess of smoky BBQ sauce, succulent beef, and melty cheese on a fluffy, toasted bun.",
    imgPath: "images/bbqBurger.png"},
    {id: "ms_burger",
    name: "Mushroom Swiss Burger",
    price: 9.99,
    description: "Savor the sizzle of bacon atop our classic burger—a perfect harmony of juicy beef, melted cheese, and crispy, smoky bacon on a toasted bun.",
    imgPath: "images/MushroomSwissBurger.png"},


    //Combos
    {id:"db_combo",
    name: "Double Burger Combo",
    price: 12.99,
    description: "The burger combo includes our signature juicy beef burger with delicious sides for a fulfilling meal.",
    imgPath: "images/DoubleBurgerCombo.png"},
    {id:"pork_combo",
    name: "Porkchop Combo",
    price: 11.99,
    description: "Our slow-cooked, juicy porkchop with sides that perfectly balance the flavors.",
    imgPath: "images/PorkCombo.png"},
    {id:"tw_combo",
    name: "Tradional Wing Combo",
    price: 11.99,
    description: "A combo that combines our signature traditional wings now in a value basket alongside our Game Fries.",
    imgPath: "images/TradionalWingCombo.png"},
    {id:"cs_combo",
    name: "Chicken Strips Combo",
    price: 11.99,
    description: "Lotum 5",
    imgPath: "images/ChickenStripsCombo.png"},


    //Wings
    {id:"gourmet_wings",
    name: "Gourmet Wings",
    price: 13.99,
    description: "Lotum 5",
    imgPath:"images/GourmetWings.png"},
    {id:"bbq_wings",
    name:"Plain Wings",
    price: 10.99,
    description: "Crispy chicken wings with no sauce, cooked to perfection",
    imgPath: "images/bbqWings.png"},
    {id:"plain_wings",
    name:"Plain Wings",
    price: 9.99,
    description: "Lotum 5",
    imgPath: "images/PlainWings.png"},

    //Sides and Appetizers
    {id:"onion_rings",
    name: "Onion Rings",
    price: 5.99,
    description: "Onion rings fried to a perfect crisp.",
    imgPath: "images/OnionRings.png"},
    {id:"fries",
    name: "Fries",
    price: 4.99,
    description: "Thinly sliced potatoes, deep-fried until golden-brown, and delicately dusted with sea salt. Crispy, fluffy perfection in every bite.",
    imgPath: "images/Fries.png"},
    {id:"chille_fries",
    name: "Chille Fries",
    price: 4.99,
    description: "lotum 5",
    imgPath: "images/ChilleFries.png"},
    {id:"mozzarella_sticks",
    name:"Mozzarella Sticks",
    price: 5.99,
    description: "Creamy mozzarella coated in a crisp batter and deep-fried to perfection. Served with tangy marinara sauce for dipping.",
    imgPath: "images/mozzarellasticks.jpg"},

    //Kids
    {id:"sliders",
    name:"Sliders",
    price: 6.99,
    description: "Two cheese burger sliders, with ketcup, fresh tomatoes, lettuce, and pickles. Comes with a side of fries.",
    imgPath: "images/chickentenders.jpg"},
    {id:"chicken_nuggets",
    name:"Chicken Nuggets Combo Platter",
    price: 6.99,
    description: "lotum 5",
    imgPath: "images/ChickenNuggetsKids.png"},
    {id:"mac_cheese",
    name:"Mac & Cheese",
    price: 6.99,
    description: "Classic elbow macaroni mixed with a creamy cheese sauce.",
    imgPath: "images/MachCheese.png"},

    //Salads
    {id:"caesar_salad",
    name:"Caesar Salad",
    price: 6.99,
    description: "comes with croutons, shedded parmesan, romaine lettuce, and caesar dressing",
    imgPath: "images/CaesarSalad.png"},
    {id:"chicken_salad",
    name:"Chicken Salad",
    price: 7.99,
    description: "comes with croutons, shedded parmesan, romaine lettuce, caesar dressing and mouth-watering chicken.",
    imgPath: "images/ChickenSalad.png"},
    {id:"balsamic_salad",
    name:"Balsamic Salad",
    price: 7.99,
    description: "lotum 5",
    imgPath: "images/BalsamicSalad.png"},

    //Sandwiches
    {id:"club_sandwich",
    name:"Club Sandwich",
    price: 5.99,
    description: "A ham, turkey, and bacon sandwich, with mouth watering tomatoes, crunchy lettuce and cheddar cheese.",
    imgPath: "images/ClubSandwich.png"},
    {id:"ruben_sandwich",
    name:"Ruben Sandwich",
    price: 5.99,
    description: "lotum 5",
    imgPath: "images/RubenSandwich.png"},
    {id:"pp_sandwich",
    name:"Pulled Pork Sandwich",
    price: 5.99,
    description: "lotum 5",
    imgPath: "images/PulledPorkSandwich.png"},

    //Drinks
    {id:"beer",
    name:"beer",
    price: 0.49,
    description: "lotum 5",
    imgPath: "images/Beer.png"},
    {id:"root_beer",
    name:"Root Beer",
    price: 1.99,
    description: "lotum 5",
    imgPath: "images/RootBeer.png"},
    {id:"strawberry_lemonade",
    name:"Strawberry Lemonade",
    price: 1.99,
    description: "Lorem ipsum dolor sit amet.",
    imgPath: "images/StrawberryLemonade.png"},
    {id:"lemonade",
    name:"Lemonade",
    price: 1.99,
    description: "This is a description",
    imgPath: "images/lemonade.jpg"},
];
