const itemDatabase = [
    {id:"gd_burger",
    name: "Game Day Burger",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/1.png"},
    {id:"wing_combo1",
    name: "Four Tradional Wings With Fries",
    price: 11.99,
    description: "A combo that combines our signature traditional wings now in a value basket alongside our Game Fries.",
    imgPath: "wing_combo1.png"},
    {id:"6wing",
    name: "Six Tradional Wings",
    price: 9.99,
    description: "Six of our signature traditional wings with a choice of sauce.",
    imgPath: "6wing.png"},
    {id:"onion_rings",
    name: "Onion Rings",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/2.png"},
    {id:"fries",
    name: "Fries",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/3.png"},
    {}
];