const itemDatabase = [
    //desserts
    {id:"apple_pie",
    name: "Apple Pie",
    price: 6.99,
    description: "This is a description",
    imgPath: "images/1.png"},
    {id:"brownie",
    name: "Brownie",
    price: 6.99,
    description: "This is a description",
    imgPath: "images/1.png"},


    //burgers
    {id:"gd_burger",
    name: "Game Day Burger",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/1.png"},
    {id:"bacon_burger",
    name: "Bacon Burger",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/1.png"},
    {id: "bbq_burger",
    name: "BBQ Burger",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/1.png"},


    //combos
    {id:"wing_combo1",
    name: "Four Tradional Wings With Fries",
    price: 11.99,
    description: "A combo that combines our signature traditional wings now in a value basket alongside our Game Fries.",
    imgPath: "images/wing_combo1.png"},

    //wings
    /*
    {id:"6wing",
    name: "Six Tradional Wings",
    price: 9.99,
    description: "Six of our signature traditional wings with a choice of sauce.",
    imgPath: "images/6wing.png"}, */
    {id:"buffalo_wings",
    name: "Buffalo Wings",
    price: 9.99,
    description: "This is a description",
    imgPath:"images/1.png"},
    {id:"plain_wings",
    name:"Plain Wings",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/1.png"},
    {id:"sampling_wings",
    name:"Sampling Wings",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/1.png"},

    //sides and appetizers
    {id:"onion_rings",
    name: "Onion Rings",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/2.png"},
    {id:"fries",
    name: "Fries",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/3.png"},
    {id:"mozzarella_sticks",
    name:"Mozzarella Sticks",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/1.png"},

    //kids
    {id:"sliders",
    name:"Sliders",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/1.png"},
    {id:"chicken_strips",
    name:"Chicken Strips",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/1.png"},
    {id:"mac_and_cheese",
    name:"Mac & Cheese",
    price: 9.99,
    description: "This is a description",
    imgPath: "images/1.png"},
];