const itemDatabase = [
    //desserts
    {id:"apple_pie",
    name: "Apple Pie",
    price: 6.99,
    description: "A pie with a buttery crust filled with a tangy-sweet apple filling.",
    imgPath: "images/1.png"},
    {id:"brownie",
    name: "Brownie",
    price: 6.99,
    description: "Rich, moist chocolate brownies with a fudge-like texture and a wallop of cocoa goodness.",
    imgPath: "images/1.png"},


    //burgers
    {id:"gd_burger",
    name: "Game Day Burger",
    price: 9.99,
    description: "A burger that's perfect for a big game day—loaded with juicy beef, melted cheese, our signature sauce, crisp lettuce and ripe tomatoes, all on a toasted bun.",
    imgPath: "images/1.png"},
    {id:"bacon_burger",
    name: "Bacon Burger",
    price: 9.99,
    description: "Savor the sizzle of bacon atop our classic burger—a perfect harmony of juicy beef, melted cheese, and crispy, smoky bacon on a toasted bun.",
    imgPath: "images/1.png"},
    {id: "bbq_burger",
    name: "BBQ Burger",
    price: 9.99,
    description: "Experience the tanginess of smoky BBQ sauce, succulent beef, and melty cheese on a fluffy, toasted bun.",
    imgPath: "images/1.png"},


    //combos
    {id:"wing_combo1",
    name: "Four Tradional Wings With Fries",
    price: 11.99,
    description: "A combo that combines our signature traditional wings now in a value basket alongside our Game Fries.",
    imgPath: "images/wing_combo1.png"},

    //wings
    /*
    {id:"6wing",
    name: "Six Tradional Wings",
    price: 9.99,
    description: "Six of our signature traditional wings with a choice of sauce.",
    imgPath: "images/6wing.png"}, */
    {id:"buffalo_wings",
    name: "Buffalo Wings",
    price: 9.99,
    description: "Spicy, tangy wings with a flavor kick made with our secret buffalo sauce. Crispy on the outside, tender on the inside.",
    imgPath:"images/1.png"},
    {id:"plain_wings",
    name:"Plain Wings",
    price: 9.99,
    description: "Our signature wings with no sauce, giving you the chance to enjoy their natural, delicious flavor.",
    imgPath: "images/1.png"},
    {id:"sampling_wings",
    name:"Sampling Wings",
    price: 9.99,
    description: "Try a sampler of our favorite wing flavors: buffalo, bbq, and original. The perfect choice for the indecisive!",
    imgPath: "images/1.png"},

    //sides and appetizers
    {id:"onion_rings",
    name: "Onion Rings",
    price: 9.99,
    description: "Sweet onions, separated into rings, coated in batter, and deep-fried to a golden crisp.",
    imgPath: "images/2.png"},
    {id:"fries",
    name: "Fries",
    price: 9.99,
    description: "Thinly sliced potatoes, deep-fried until golden-brown, and delicately dusted with sea salt. Crispy, fluffy perfection in every bite.",
    imgPath: "images/3.png"},
    {id:"mozzarella_sticks",
    name:"Mozzarella Sticks",
    price: 9.99,
    description: "Creamy mozzarella coated in a crisp batter and deep-fried to perfection. Served with tangy marinara sauce for dipping.",
    imgPath: "images/1.png"},

    //kids
    {id:"sliders",
    name:"Sliders",
    price: 9.99,
    description: "Bite-sized burgers served on mini-buns. Perfectly suited for tiny hands and appetites! Served with a side of fries.",
    imgPath: "images/1.png"},
    {id:"chicken_strips",
    name:"Chicken Strips",
    price: 9.99,
    description: "Strips of chicken breast coated in breadcrumbs and deep-fried until golden. A favorite among our young diners!",
    imgPath: "images/1.png"},
    {id:"mac_and_cheese",
    name:"Mac & Cheese",
    price: 9.99,
    description: "Classic elbow macaroni mixed with a creamy, tangy cheese sauce.",
    imgPath: "images/1.png"}
];